sudo: false

language: node_js

notifications:
  email: false

node_js:
  - stable

cache:
  directories:
    - node_modules

before_script:
  - npm prune

script:
  - npm run lint
  - npm run flow
  - npm run test:coverage
  - npm run build

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run codecov; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run release; fi'

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
