/**
 * Copyright (c) 2017 CA. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

// flow-typed signature: 6d72d33334cabc24f0ad585b5d50e506
// flow-typed version: <<STUB>>/jss-preset-default_v^1.2.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss-preset-default'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss-preset-default' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss-preset-default/dist/jss-preset-default' {
  declare module.exports: any;
}

declare module 'jss-preset-default/dist/jss-preset-default.min' {
  declare module.exports: any;
}

declare module 'jss-preset-default/lib/index' {
  declare module.exports: any;
}

declare module 'jss-preset-default/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss-preset-default/dist/jss-preset-default.js' {
  declare module.exports: $Exports<'jss-preset-default/dist/jss-preset-default'>;
}
declare module 'jss-preset-default/dist/jss-preset-default.min.js' {
  declare module.exports: $Exports<'jss-preset-default/dist/jss-preset-default.min'>;
}
declare module 'jss-preset-default/lib/index.js' {
  declare module.exports: $Exports<'jss-preset-default/lib/index'>;
}
declare module 'jss-preset-default/webpack.config.js' {
  declare module.exports: $Exports<'jss-preset-default/webpack.config'>;
}
