// flow-typed signature: a0298300ee39d936f4c6ec532da47195
// flow-typed version: <<STUB>>/object.omit_v^2.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object.omit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object.omit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'object.omit/index' {
  declare module.exports: $Exports<'object.omit'>;
}
declare module 'object.omit/index.js' {
  declare module.exports: $Exports<'object.omit'>;
}
