/**
 * Copyright (c) 2016 CA. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

// flow-typed signature: 0553d70edd489cb41aeb549f4ae988a9
// flow-typed version: <<STUB>>/react-themer_vgit+ssh://git@github.com:CAAPIM/react-themer.git/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-themer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-themer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-themer/flow-typed/themer' {
  declare module.exports: any;
}

declare module 'react-themer/lib/index' {
  declare module.exports: any;
}

declare module 'react-themer/lib/react-themer/index' {
  declare module.exports: any;
}

declare module 'react-themer/lib/theme-provider/index' {
  declare module.exports: any;
}

declare module 'react-themer/lib/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-themer/flow-typed/themer.js' {
  declare module.exports: $Exports<'react-themer/flow-typed/themer'>;
}
declare module 'react-themer/lib/index.js' {
  declare module.exports: $Exports<'react-themer/lib/index'>;
}
declare module 'react-themer/lib/react-themer/index.js' {
  declare module.exports: $Exports<'react-themer/lib/react-themer/index'>;
}
declare module 'react-themer/lib/theme-provider/index.js' {
  declare module.exports: $Exports<'react-themer/lib/theme-provider/index'>;
}
declare module 'react-themer/lib/utils/index.js' {
  declare module.exports: $Exports<'react-themer/lib/utils/index'>;
}
