/**
 * Copyright (c) 2017 CA. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

// flow-typed signature: 8b30dc1187edd97e46d693d564aae8a7
// flow-typed version: <<STUB>>/themer_v^1.2.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'themer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'themer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'themer/bin/themer' {
  declare module.exports: any;
}

declare module 'themer/lib/index' {
  declare module.exports: any;
}

declare module 'themer/lib/middleware/index' {
  declare module.exports: any;
}

declare module 'themer/lib/theme/index' {
  declare module.exports: any;
}

declare module 'themer/lib/Themer' {
  declare module.exports: any;
}

declare module 'themer/lib/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'themer/bin/themer.js' {
  declare module.exports: $Exports<'themer/bin/themer'>;
}
declare module 'themer/lib/index.js' {
  declare module.exports: $Exports<'themer/lib/index'>;
}
declare module 'themer/lib/middleware/index.js' {
  declare module.exports: $Exports<'themer/lib/middleware/index'>;
}
declare module 'themer/lib/theme/index.js' {
  declare module.exports: $Exports<'themer/lib/theme/index'>;
}
declare module 'themer/lib/Themer.js' {
  declare module.exports: $Exports<'themer/lib/Themer'>;
}
declare module 'themer/lib/utils/index.js' {
  declare module.exports: $Exports<'themer/lib/utils/index'>;
}
