/**
 * Copyright (c) 2017 CA. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@caapim/themer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@caapim/themer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@caapim/themer/bin/themer' {
  declare module.exports: any;
}

declare module '@caapim/themer/lib/index' {
  declare module.exports: any;
}

declare module '@caapim/themer/lib/middleware/index' {
  declare module.exports: any;
}

declare module '@caapim/themer/lib/theme/index' {
  declare module.exports: any;
}

declare module '@caapim/themer/lib/Themer' {
  declare module.exports: any;
}

declare module '@caapim/themer/lib/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@caapim/themer/bin/themer.js' {
  declare module.exports: $Exports<'@caapim/themer/bin/themer'>;
}
declare module '@caapim/themer/lib/index.js' {
  declare module.exports: $Exports<'@caapim/themer/lib/index'>;
}
declare module '@caapim/themer/lib/middleware/index.js' {
  declare module.exports: $Exports<'@caapim/themer/lib/middleware/index'>;
}
declare module '@caapim/themer/lib/theme/index.js' {
  declare module.exports: $Exports<'@caapim/themer/lib/theme/index'>;
}
declare module '@caapim/themer/lib/Themer.js' {
  declare module.exports: $Exports<'@caapim/themer/lib/Themer'>;
}
declare module '@caapim/themer/lib/utils/index.js' {
  declare module.exports: $Exports<'@caapim/themer/lib/utils/index'>;
}
